# ejercicio 1


$F=\frac{1}{4\pi e_{0}} \frac{qQx}{(x^{2}+a^{2})^{3/2}}$

Donde $e_{0}=8.85×10^{-12} C^{2}/Nm^{2}$ . Encuentre la distancia  x   donde la fuerza es de 1 N, si q y Q son $2×10^{-5}C$ para un anillo con un radio de $a=0.9 m$.  Usando los métodos

Bisección

Falsa posición. 

Newton

Secante

Para todos los incisos considere una tolerancia de 0.001% o el número de iteraciones no supere a 100. 
Para los métodos que usan intervalos considerar intervalos iniciales a ±0.1 de la raíz. 


resolviendo la ecuacion


$1=\frac{1}{4\pi (8.885 * 10^{-12})} \frac{(2×10^{-5})(2×10^{-5})x}{(x^{2}+0.9^{2})^{3/2}}$

$1=\frac{1}{4\pi (8.885 * 10^{-12})} \frac{(4×10^{-10})x}{(x^{2}+0.9^{2})^{3/2}}$

$1=\frac{1}{\pi (8.885)} \frac{(10^{2})x}{(x^{2}+0.9^{2})^{3/2}}$

$1=0.035.96.72 \frac{100x}{(x^{2}+0.9^{2})^{3/2}}$

$1=\frac{3.59672x}{(x^{2}+0.9^{2})^{3/2}}$

metodo de la biseccion

In [70]:
#definiomos la funcion
def f1(x):
    aux=(3.59672*x)/((x**2+0.81)**3/2) -1
    return (aux)
#%%


como se ve en el grafico existe una raíz en el intervalo  [0.221; 1.5 ].

In [65]:
# Programa Bisección    
# a: limite inferior del intervalo
# b: limete superior  del intervalo
# ck: punto medio
# fx: función a obtener la raiz
# tol: tolerancia
# ea: error aproximado    
# ERA: error relativo aproximado (en %)        
# nk: número de iteraciones
from math import *
import numpy as np
def bisec(a,b,fx,tol,nk):
    xk_old=b
    print("iter","a"," ","b"," ", "xk"," ", "f(xk)"," ", "ERA" )
    for i in range(1,nk):
        xk = (a+b)/2
        ERA = 100*abs(xk - xk_old)/abs(xk) # error relativo aproximado
        print(i,round(a,6)," ",round(b,6)," ",round(xk,6)," ", abs(round(fx(xk),5))," ", round(ERA,5))
        if(fx(a)*fx(xk)<0):
            b=xk
        else: a=xk
        xk_old =xk
        if(ERA<tol):
            break
#    xr=(a+b)/2 # raiz aproximada
    aux = fx(xk) # función evaluada en la raíz
    return(xk,aux)

In [71]:
bisec(0.221,1.5,f1, 0.001,40 )

iter a   b   xk   f(xk)   ERA
1 0.221   1.5   0.8605   0.66076   74.31726
2 0.8605   1.5   1.18025   0.2059   27.09172
3 0.8605   1.18025   1.020375   0.15707   15.66826
4 1.020375   1.18025   1.100313   0.0407   7.26498
5 1.020375   1.100313   1.060344   0.05388   3.76941
6 1.060344   1.100313   1.080328   0.00554   1.84984
7 1.080328   1.100313   1.09032   0.01784   0.91645
8 1.080328   1.09032   1.085324   0.00621   0.46033
9 1.080328   1.085324   1.082826   0.00035   0.2307
10 1.080328   1.082826   1.081577   0.00259   0.11548
11 1.081577   1.082826   1.082202   0.00112   0.05771
12 1.082202   1.082826   1.082514   0.00038   0.02885
13 1.082514   1.082826   1.08267   2e-05   0.01442
14 1.08267   1.082826   1.082748   0.00017   0.00721
15 1.08267   1.082748   1.082709   8e-05   0.00361
16 1.08267   1.082709   1.08269   3e-05   0.0018
17 1.08267   1.08269   1.08268   1e-05   0.0009


(1.0826798019409178, -6.521856217189814e-06)

metodo de falsa posicion

In [72]:
#=====================#
# a: limite inferior del intervalo
# b: limete superior  del intervalo
# fx: función a obtener la raiz
# nk: número de iteraciones    
# tol: tolerancia (en %)
# ERA: error relativo aproximado
def falsa_posi(a,b,fx,nk,tol):
    print("iter","a"," ","b"," ", "xi"," ","f(ck)"," ", "E_RA")
    x0 = b
    for i in range(0,nk):
        xi = (a*fx(b) - b*fx(a))/(fx(b) - fx(a))
        ERA = 100*abs(xi - x0)/abs(xi) # error relativo aproximado
        print(i+1,round(a,6)," ",round(b,6)," ",round(xi,6)," ", 
              abs(round(fx(xi),7))," ",round(ERA,5))        
        if(fx(a)*fx(xi)<0):
            b=xi
        else: a=xi
        x0=xi
        if(ERA<tol):
            break
    aux = fx(xi)
    return(xi,aux)
#%%

In [73]:
falsa_posi(0.221, 1.5, f1, 40, 0.001)

iter a   b   xi   f(ck)   E_RA
1 0.221   1.5   1.126174   0.0975192   33.19439
2 0.221   1.126174   1.071245   0.0272495   5.12751
3 1.071245   1.126174   1.083242   0.0013281   1.10745
4 1.071245   1.083242   1.082684   1.68e-05   0.05149
5 1.071245   1.082684   1.082677   2e-07   0.00065


(1.0826771209832113, -2.1203068822917004e-07)

metodo newton

In [74]:
# metodo de N-R
# x0: raiz inicial
# Nmax: número de iteraciones máxima    
# tol: tolerancia (ERA)
# fx: función a encontrar la raíz     
# dfx: derivada de la función fx    
# NOTA: la función evaluada en la raíz aproximada, fx(xk),
#       es mostrada en  valor absoluto
def newtonr(x0,Nmax,tol,fx,dfx):
    ERA = 100
    iter = 0
    print("iter", " ", "xk", " ", "fx(xk)", " ", "EA", " ", "ERA" )
    while(ERA>tol):
        xk = x0 - ( fx(x0)/dfx(x0) )
        iter= iter + 1
        EA = abs(xk-x0)
        ERA= 100*(EA/abs(xk))
        x0 = xk
        if(iter > Nmax):
            return
        print( iter," ",round(xk,7)," ",round(abs(fx(xk)),8)," ", round(EA,8), 
              " ", round(ERA,8) ) 
    aux = abs(fx(xk))
    return(xk,aux)        
      
#%%

In [76]:
#derivada de la funcion
def df2x(x):
    aux=(-17983600*x**2 +7283358)/(25*(100*x**2+81*x)**(1/2)*(100*x**2+81)**2)
    return aux

In [77]:
newtonr( 0.221, 80, 0.001, f1, df2x )

iter   xk   fx(xk)   EA   ERA
1   0.013552   0.81668832   0.20744798   1530.75350901
2   0.0330001   0.55511686   0.01944805   58.93336825
3   0.0539639   0.27738147   0.02096382   38.84786395
4   0.0676477   0.09968526   0.01368379   20.22802604
5   0.073243   0.02804255   0.00559531   7.63938458
6   0.0748925   0.00704657   0.00164947   2.20244766
7   0.0753125   0.00170945   0.00042002   0.55770391
8   0.0754147   0.00041094   0.00010224   0.1355644
9   0.0754393   9.857e-05   2.46e-05   0.03260435
10   0.0754452   2.363e-05   5.9e-06   0.00782127
11   0.0754466   5.66e-06   1.41e-06   0.00187502
12   0.075447   1.36e-06   3.4e-07   0.00044944


(0.0754469668379987, 1.3575382096231436e-06)

metodo de la secante

In [78]:
#%%
# metodo de la secante
# x0=x_(0)
# x1=x_(1)
# tol: tolerancia en porcentaje
# Nmax: número de iteraciones
# fx: función f(x) a encontrar la raíz
def secante(x0,x1,Nmax,tol,fx):
    ERA = 100
    iter = 1
    print("iter", " ", "xk", " ", "fx(xk)", " ", "EA", " ", "ERA" )
    while(ERA>tol):
        # xk: genera la raiz
        xk = x1 - (fx(x1)*(x1 - x0))/(fx(x1)-fx(x0))
        iter = iter + 1
        EA = abs(xk-x1)
        ERA = abs((xk-x1)/xk)*100
        x0 = x1
        x1 = xk
        if(iter > Nmax):
            return
        print(iter," ",round(xk,7)," ",round(fx(xk),9)," ",
              round(EA,8), " ", round(ERA,8) )
    aux = abs(fx(xk))
    return(xk,aux)   
#------------------------------#

In [79]:
secante(0.221, 1.5, 80,0.001,f1)

iter   xk   fx(xk)   EA   ERA
2   1.1261736   -0.09751917   0.37382643   33.19438827
3   1.0568532   0.062545589   0.06932034   6.55912654
4   1.0839403   -0.002968973   0.02708705   2.49894269
5   1.0827128   -8.4073e-05   0.00122752   0.11337486
6   1.082677   1.18e-07   3.577e-05   0.00330411
7   1.082677   -0.0   5e-08   4.64e-06


(1.0826770308965776, 4.704570066849101e-12)

# ejecrcicio 2

Determine las raíces de las siguientes ecuaciones no lineales  por medio del Newton-Raphson (5 puntos)

Utilice el  valor inicial de $x_{0}=(0,1,1)^{2}$  e haga iteraciones hasta que $‖x_{k-1}-xk‖_{\infty
}<10-6$. Compruebe sus resultados, esto es, reemplace la solución encontrada en el sistema de ecuaciones y verifique la igualdad.

$xy-cos ( x)+z^{2}-3.6=0$

$x^{2}-2y^{2}+z-2.8 =0$

$3x+ysin ( z)-2.8 = 0$


cargando las librerias 

In [1]:
from math import *
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

In [2]:
# NORMA INFINITO
def infvector(x):
    norma=max(abs(x))
    return(norma)

In [3]:
#%%
# METODO DE NEWTON-RAPHSON PARA SISTEMAS DE ECCUAIONES NO LINEALES    
# Fx: Sistema de ecuaciones no lineales. Es un vector
# JFx: Matriz jacobiana
# x0 vector inicial 
# imax: iteraciones maximas
# tol: tolerancia para la norma infinito
#---------------------#
def newton_jacob(Fx, JFx, x0, imax, tol):
    EA=10
    iter=0
    print("itera"," xk", "error aprox", "verificacion")
    while(EA>tol):
        xk = x0 - inv( JFx(x0)).dot(Fx(x0))
        iter = iter + 1
        difk = xk - x0
        #print(difk)
        EA = infvector(difk)
        x0 = xk
        if(iter>imax):
            return
        print( iter," | ",xk," | ",EA," | ", Fx(xk) )
#        print(xk)



In [28]:
# VECTOR 
# función F(x,y,z) = ( f1(x,y,z), f2(x,y,z), f3(x,y,z) ) =  (0,0,0)
def F_sis(xvec):
    x=xvec[0] 
    y=xvec[1] 
    z=xvec[2]
    Fx = np.array([0.0, 0.0, 0.0])
    Fx[0] = x*y - cos(x) + z**2
    Fx[1] = x**2 -2*y**2 + z
    Fx[2] = 3*x + y*sin(z)
    return(Fx)

In [29]:
#==============#
# matriz jacobiana
def Jxy(xvec):
    x=xvec[0]
    y=xvec[1]
    z=xvec[2]
    jaco = np.zeros((3,3))
    jaco[0,0] = y + sin(x) 
    jaco[1,0] = 2*x
    jaco[2,0] = 3
    jaco[0,1] = x 
    jaco[1,1] = -4*y
    jaco[2,1] = sin(z)
    jaco[0,2] = 2*z
    jaco[1,2] = 1
    jaco[2,2] = y*cos(z)
    return(jaco)
#=================#

In [37]:
F_sis( np.array([3,3,3]) )
Jxy( np.array([3,3,3]) )

array([[  3.14112001,   3.        ,   6.        ],
       [  6.        , -12.        ,   1.        ],
       [  3.        ,   0.14112001,  -2.96997749]])

In [38]:
#punto inicial 
x0=np.array([0,1,1])
tol=0.000001
Nmax=80
##
newton_jacob(F_sis, Jxy, x0, Nmax, tol)

itera  xk error aprox verificacion
1  |  [-0.24045097  0.78005637  1.12022548]  |  0.24045096988228098  |  [ 0.09610915 -0.03893373 -0.01914721]
2  |  [-0.21848435  0.74762652  1.06853456]  |  0.05169092864761948  |  [ 0.00219431 -0.00162086 -0.00016143]
3  |  [-0.21797646  0.74658931  1.06727556]  |  0.0012589928867761113  |  [ 1.18418963e-06 -1.89365770e-06  1.10144217e-07]
4  |  [-0.21797614  0.74658838  1.06727483]  |  9.250462260634862e-07  |  [ 2.84883228e-13 -1.60849112e-12  1.51545443e-13]


# ejercicio 3

Halle la solución del sistema (5 puntos)


\begin{equation}
\begin{bmatrix}
-2 & -1 & 0 & 0\\
0 & 0 & -1 & 1\\
0 & -1 & 2 & -1\\
-1 & 2 & -1 & 0
\end{bmatrix}
\quad
\begin{bmatrix}
x_{1} \\
x_{2} \\
x_{3} \\
x_{4} 
\end{bmatrix}
=\begin{bmatrix}
1 \\
0 \\
0 \\
0  
\end{bmatrix}
\end{equation}

Resuelva el sistema por:
    
Eliminación gaussiana 

Descomposición LU

Sustituya la solución obtenida en el sistema de ecuaciones para verificar su resultado.


In [53]:
A = np.array([[-2.0,-1,0 ,0.0 ],[0.0, 0.0, -1.0, 1.0],[0.0, -1.0, 2.0, -1.0],[-1.0, 2.0, -1.0, 0.0]])
b = np.array([[1.0],[0.0],[0.0],[0.0]])

In [54]:
# Solución del sistema Ax=b por medio de facotización LU
# Para la factorización LU se considera el método de Doolittle

import numpy as np
#
def LU_gauss_sistem(A,b):
    # renombrando
    A1=A.copy(); b1=b.copy()
    # dimension de la matriz
    n = len(A1) 
  # fase de eliminación
  # j: columnas -- i: filas
# MATRIZ L
    L = np.identity(n)  
#------- FASE DE ELIMINACIÓN -------------#  
  # se inicia con las columnas
    for j in range(0,n-1):
        for i in range(j+1,n):
            # condicion del pivote diferente de cero 
            # A[i,j] -> fila posterior a la primera fila
           if A1[i,j]!= 0.0:
               factor = A1[i,j]/A1[j,j] # A[j,j]-> diagonal pivote
               # F2 = F2 - factor*F1
#               A[i,(j+1):n] = A[i,(j+1):n] - factor*A[j,(j+1):n]
               A1[i,j:n] = A1[i,j:n] - factor*A1[j,j:n]
               if i>j:
                   L[i,j] = factor
    U=A1
    print("--------------------------------")
    print("matriz triangular inferior --> L")
    print(L)
    print("--------------------------------")    
    print("matriz triangular superior --> U")    
    print(U)
    print("--------------------------------")    
    print("verificacion --> A=LU")
    print(L@U)
#------- SUSTITUCION HACIA ADELANTE -------------#    
# Ly=b
    ys=np.zeros(n) #-> vector solucion y's
    ys[0]=b1[0]    
    for ix in range(1,n):
        suma=0
        for jx in range(0,ix):
            suma = suma + L[ix,jx]*ys[jx]
        ys[ix]=b1[ix] - suma
#    print(ys)
#------- SUSTITUCION HACIA ATRAS -------------#    
#   Ux=y    
    xs=np.zeros(n) #-> vector solucion x's
    xs[(n-1)]=ys[(n-1)]/U[(n-1),(n-1)]
    for ix in reversed(range(n-1)):
        suma=0
        for jx in range(ix,n):
            suma = suma + U[ix,jx]*xs[jx]
        xs[ix]=(ys[ix]-suma)/U[ix,ix]     
    return(xs)    

In [55]:
def gaussElimin(A,b):
    # renombrando
    A1=A.copy(); b1=b.copy()
    # dimension de la matriz
    n = len(b1) 
# fase de eliminación
# # i: filas ; j: columnas
#------- FASE DE ELIMINACIÓN -------------#  
  # se inicia con las columnas
    for j in range(0,n-1):
        for i in range(j+1,n):
            # condicion del pivote diferente de cero 
            # A[i,j] -> fila posterior a la primera fila
           if A1[i,j]!= 0.0:
               factor = A1[i,j]/A1[j,j] # A[j,j]-> diagonal pivote
               # F2 = F2 - factor*F1
#               A[i,(j+1):n] = A[i,(j+1):n] - factor*A[j,(j+1):n]
               A1[i,j:n] = A1[i,j:n] - factor*A1[j,j:n]      
              # operación sobre el vector b
               b1[i] = b1[i] - factor*b1[j]
    print("--------------------------------")               
    print("eliminacion hacia adelante -> MATRIZ - U  ")               
    print(A1)
#    print(b1)
#------- SUSTITUCIÓN HACIA ATRAS  -------------#    
    xs=np.zeros(n) #-> vector solucion x's
    xs[(n-1)]=b1[(n-1)]/A1[(n-1),(n-1)]
    for ix in reversed(range(n-1)):
        suma=0
        for jx in range(ix,n):
            suma = suma + A1[ix,jx]*xs[jx]
        xs[ix]=(b1[ix]-suma)/A1[ix,ix]     
    return(xs)

In [56]:
gaussElimin(A,b)

--------------------------------
eliminacion hacia adelante -> MATRIZ - U  
[[ -2.  -1.   0.   0.]
 [  0.   0.  -1.   1.]
 [  0.  nan -inf  inf]
 [  0.  nan  nan  nan]]


C:\Users\MIPC~1\AppData\Local\Temp/ipykernel_10440/3418685383.py:15: RuntimeWarning: divide by zero encountered in double_scalars
  factor = A1[i,j]/A1[j,j] # A[j,j]-> diagonal pivote
C:\Users\MIPC~1\AppData\Local\Temp/ipykernel_10440/3418685383.py:18: RuntimeWarning: invalid value encountered in multiply
  A1[i,j:n] = A1[i,j:n] - factor*A1[j,j:n]
C:\Users\MIPC~1\AppData\Local\Temp/ipykernel_10440/3418685383.py:20: RuntimeWarning: invalid value encountered in multiply
  b1[i] = b1[i] - factor*b1[j]
C:\Users\MIPC~1\AppData\Local\Temp/ipykernel_10440/3418685383.py:15: RuntimeWarning: invalid value encountered in double_scalars
  factor = A1[i,j]/A1[j,j] # A[j,j]-> diagonal pivote
C:\Users\MIPC~1\AppData\Local\Temp/ipykernel_10440/3418685383.py:31: RuntimeWarning: invalid value encountered in double_scalars
  suma = suma + A1[ix,jx]*xs[jx]


array([nan, nan, nan, nan])

In [57]:
LU_gauss_sistem(A,b)

--------------------------------
matriz triangular inferior --> L
[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [ 0.  -inf  1.   0. ]
 [ 0.5  inf  nan  1. ]]
--------------------------------
matriz triangular superior --> U
[[ -2.  -1.   0.   0.]
 [  0.   0.  -1.   1.]
 [  0.  nan -inf  inf]
 [  0.  nan  nan  nan]]
--------------------------------
verificacion --> A=LU
[[-2. nan nan nan]
 [ 0. nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]


C:\Users\MIPC~1\AppData\Local\Temp/ipykernel_10440/1189713513.py:22: RuntimeWarning: divide by zero encountered in double_scalars
  factor = A1[i,j]/A1[j,j] # A[j,j]-> diagonal pivote
C:\Users\MIPC~1\AppData\Local\Temp/ipykernel_10440/1189713513.py:25: RuntimeWarning: invalid value encountered in multiply
  A1[i,j:n] = A1[i,j:n] - factor*A1[j,j:n]
C:\Users\MIPC~1\AppData\Local\Temp/ipykernel_10440/1189713513.py:22: RuntimeWarning: invalid value encountered in double_scalars
  factor = A1[i,j]/A1[j,j] # A[j,j]-> diagonal pivote
C:\Users\MIPC~1\AppData\Local\Temp/ipykernel_10440/1189713513.py:37: RuntimeWarning: invalid value encountered in matmul
  print(L@U)
C:\Users\MIPC~1\AppData\Local\Temp/ipykernel_10440/1189713513.py:45: RuntimeWarning: invalid value encountered in double_scalars
  suma = suma + L[ix,jx]*ys[jx]
C:\Users\MIPC~1\AppData\Local\Temp/ipykernel_10440/1189713513.py:55: RuntimeWarning: invalid value encountered in double_scalars
  suma = suma + U[ix,jx]*xs[jx]


array([nan, nan, nan, nan])

# ejercicio 4

Halle la solución del sistema (5 puntos)


\begin{equation}
\begin{bmatrix}
16 & 2 & -3\\
23 & 42 & -4\\
5 & -9 & 32
\end{bmatrix}
\quad
\begin{bmatrix}
x_{1} \\
x_{2} \\
x_{3}
\end{bmatrix}
=\begin{bmatrix}
34 \\
88 \\
1
\end{bmatrix}
\end{equation}

Usando el método de Gauss-Seidel, considerando como punto inicial [0,0,0], con una tolerancia de $10^{7}$ y con un máximo de 50 iteraciones

In [58]:
#%%
from math import *
import numpy as np
from numpy.linalg import inv
#----------------------------------------#
#%%
# A : MATRIZ DEL SISTEMA
def diagdomin(A):
    aii  = abs(np.diag(A))
    aux = np.sum( abs( A-np.diag(np.diag(A)) ),axis=1 )
    if np.all(aii > aux): 
        print("es diagonal dominante")
    else:
        print("no es diagonal dominante")
    return
# norma infinito de un vector
def infvector(x):
    norma=max(abs(x))
    return(norma)

In [59]:
#%%
# A : MATRIZ DE COEFICIENTES
# b: VECTOR b
# N: NUMERO DE ITERACIONES MAXIMAS
# x0: VECTOR INICIAL
# tol: TOLERANCIA    
# np.tril(A) = L + D
# np.triu(A,1) = U, con ceros en la diagonal    
def gauss_seidel_sis(A,b,N,x0,tol):
    LDinv=inv(np.tril(A))
    U = np.triu(A,1)
    print("iter")
    for i in range(1,N):
        xk  = - np.dot( LDinv, np.dot(U,x0)) + np.dot(LDinv,b)
        ERA = infvector(xk-x0)
        x0=xk
        print(i," | ",xk," | ",ERA," | ")
        if(ERA<tol):
            break
    return(xk)

In [62]:
# matriz de coeficientes
A=np.array( [[16.0,2,-3], [23.0, 42, -4,], [5.0,-9,32]] )
# vector b
b=np.array([ 34.0, 88, 1 ])
# Numero de iteraciones
N=50
# vector inicial (vector solucion aproximado) 
x0=np.array([0.0, 0, 0 ])
# tolerancia
tol=10**(-7)  

In [63]:
# VERIFICAR QUE LA MATRIZ SEA ESTRICTAMENTE DIAGONAL DOMINANTE
diagdomin(A)
# APLICANDO EL METODO DE JACOBI (GAUSS-JACOBI)
xsol=gauss_seidel_sis(A,b,N,x0,tol)
xsol
# VERIFICAR LA SOLUCION
A.dot(xsol)

es diagonal dominante
iter
1  |  [ 2.125       0.93154762 -0.03878348]  |  2.1250000000000004  | 
2  |  [ 2.00128464e+00  9.95602839e-01 -1.43742724e-03]  |  0.12371535528273814  | 
3  |  [ 2.00028013e+00  9.99709699e-01 -1.25417076e-04]  |  0.0041068598938585055  | 
4  |  [ 2.00001277e+00  9.99981061e-01 -7.32210280e-06]  |  0.0002713623576170443  | 
5  |  [ 2.00000099e+00  9.99998758e-01 -5.04668850e-07]  |  1.7696716646975474e-05  | 
6  |  [ 2.00000006e+00  9.99999919e-01 -3.23244598e-08]  |  1.160657434495782e-06  | 
7  |  [ 2.00000000e+00  9.99999995e-01 -2.13678141e-09]  |  7.593529771643404e-08  | 


array([34.00000006, 87.99999988,  1.        ])